[package]
name = "crc-trim-prefix"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3"

[dev-dependencies]
rand_xoshiro = "0.6.0"

[profile.release]
strip = true
